### ISSUE TITLE
kspapi extension

### ISSUE THREAD

**Issue by MollyDolly** [ItMustBeACamel/ProcAirships#21]
![Annotation 2020-02-16 165925](https://user-images.githubusercontent.com/16492813/74615417-bd2c1a00-50dd-11ea-9a26-dff8bc484841.png)
hello 
Im getting the error on load "kspapi extension incompatible with 1.9.0 as this was installed from Ckan this afternoon. 
path of plugin Kerbal Space Program1.9.0\GameData\ProcAirships\Plugins\KSPAPIExtensions.dll

game load screen shows this under the mod manager loaded patches.
Kerbal Space Program1.7.2.0\GameData\ProcAirships\Plugins\KSPAPIExtensions.dll

**Comment by plushugh** [comment]
yes, this mod is REALLY old and is not compatible with ksp 0.9 or later......
